# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 11:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='mr', max_length=3)),
                ('name', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.City')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('test_name', models.CharField(default='simple blood test', max_length=200)),
                ('glucose', models.CharField(default='', max_length=100)),
                ('hba1c', models.CharField(default='', max_length=100)),
                ('rbc', models.CharField(default='', max_length=100)),
                ('wbc', models.CharField(default='', max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Person')),
            ],
        ),
    ]
